# Generated by Django 3.0.5 on 2021-05-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.IntegerField(choices=[('Tổng hợp', 0), ('Xã hội', 1), ('Thế giới', 2), ('Kinh doanh', 3), ('Công nghệ', 4), ('Thể thao', 5), ('Giải trí', 6)], default=0),
        ),
    ]
